import Foundation

// Textes du cartouche dépliable
let infoText: [String: String] = [
    "Mercure": "La plus petite planète et la plus rapide : 88 jours pour boucler son orbite. Sans atmosphère pour amortir quoi que ce soit, sa surface passe de −170 °C la nuit à 430 °C au soleil. BepiColombo doit s’y mettre en orbite fin 2026.",
    "Vénus": "Presque la jumelle de la Terre par la taille, l’enfer en plus : 92 bars de gaz carbonique et 465 °C au sol, de quoi fondre le plomb. Elle tourne à l’envers, et si lentement qu’un jour vénusien dure plus longtemps que son année.",
    "Terre": "La seule planète où l’eau liquide tient en surface, protégée par un champ magnétique et une atmosphère d’azote et d’oxygène. Son axe incliné de 23,44° donne les saisons ; la Lune stabilise cette inclinaison depuis quatre milliards d’années.",
    "Mars": "Deux fois plus petite que la Terre, avec une atmosphère cent fois plus ténue. On y trouve le plus haut volcan du système solaire, Olympus Mons et ses 22 km, et les lits de rivières taries il y a trois milliards d’années.",
    "Jupiter": "Deux fois et demie plus massive que toutes les autres planètes réunies. Sa Grande Tache rouge est un anticyclone suivi depuis le XVIIᵉ siècle, et son champ magnétique, le plus puissant après celui du Soleil, s’étend au-delà de l’orbite de Saturne.",
    "Saturne": "Ses anneaux s’étalent sur 280 000 km mais ne font que quelques dizaines de mètres d’épaisseur, presque uniquement de la glace d’eau. La planète, elle, est si peu dense qu’elle flotterait sur l’eau.",
    "Uranus": "Basculée à 98°, elle roule sur son orbite : chaque pôle reste 21 ans en plein soleil, puis 21 ans dans le noir. Une seule sonde l’a visitée, Voyager 2 en janvier 1986.",
    "Neptune": "Découverte en 1846 par le calcul avant d’être observée. Ses vents atteignent 2 100 km/h, les plus violents du système solaire, et il lui faut 165 ans pour faire le tour du Soleil.",
    "Lune": "À 384 400 km, elle nous montre toujours la même face et s’éloigne de 3,8 cm par an. Douze personnes y ont marché entre 1969 et 1972.",
    "Phobos": "22 km de diamètre, un caillou qui orbite à 6 000 km de Mars — trois fois par jour martien. Elle descend de quelques centimètres par siècle et finira disloquée en anneau.",
    "Deimos": "12 km à peine. Vue depuis Mars, elle ressemble à une étoile brillante qui met deux jours à traverser le ciel.",
    "Io": "Le corps le plus volcanique du système solaire : plus de 400 volcans actifs, alimentés par le pétrissage de marée entre Jupiter et les autres lunes.",
    "Europe": "Sous 15 à 25 km de glace, un océan salé qui contiendrait deux fois plus d’eau que tous ceux de la Terre. C’est la cible d’Europa Clipper et de JUICE.",
    "Ganymède": "La plus grosse lune du système solaire, plus grande que Mercure, et la seule à posséder son propre champ magnétique.",
    "Callisto": "La surface la plus cratérisée que l’on connaisse, inchangée depuis quatre milliards d’années. Assez loin de Jupiter pour échapper à ses ceintures de radiation.",
    "Mimas": "Son cratère Herschel fait le tiers de son diamètre : l’impact a failli la briser.",
    "Encelade": "Des geysers d’eau salée jaillissent de son pôle sud. Cassini les a traversés et y a trouvé des molécules organiques : un océan global se cache sous la glace.",
    "Téthys": "Presque uniquement de la glace d’eau, entaillée par Ithaca Chasma, un canyon de 2 000 km de long.",
    "Dioné": "Ses falaises de glace, prises pour de simples traînées brillantes par Voyager, font plusieurs centaines de mètres de haut.",
    "Rhéa": "Deuxième lune de Saturne par la taille : un monde de glace criblé de cratères.",
    "Titan": "La seule lune dotée d’une vraie atmosphère, plus dense que celle de la Terre. Il y pleut du méthane, qui remplit lacs et rivières. Huygens s’y est posé en 2005 ; l’hélicoptère Dragonfly doit y voler.",
    "Japet": "Un hémisphère noir comme du charbon, l’autre blanc comme la neige, et une crête équatoriale de 13 km de haut qui en fait le tour.",
    "Miranda": "Un patchwork de terrains qui semblent recollés, avec Verona Rupes, une falaise de 20 km : la plus haute connue.",
    "Ariel": "La surface la plus jeune du système d’Uranus, striée de vallées de glace.",
    "Umbriel": "La plus sombre des grandes lunes d’Uranus, marquée d’un anneau lumineux resté inexpliqué.",
    "Titania": "La plus grande lune d’Uranus, fracturée par des canyons longs de 1 600 km.",
    "Obéron": "La plus extérieure des grandes lunes d’Uranus, criblée de cratères aux fonds sombres.",
    "Protée": "L’une des plus grosses lunes irrégulières connues : un peu plus de masse et sa gravité l’aurait arrondie.",
    "Triton": "Elle tourne à contresens de Neptune : c’est un objet de la ceinture de Kuiper capturé. Des geysers d’azote y jaillissent par −235 °C.",
    "Néréide": "Son orbite est l’une des plus excentriques connues : elle passe de 1,4 à 9,7 millions de kilomètres de Neptune.",
    "Voyager 1": "Lancée le 5 septembre 1977, elle survole Jupiter en 1979 puis Saturne en 1980 ; l’assistance de Titan l’éjecte hors du plan des planètes. Depuis le 25 août 2012 elle navigue dans le milieu interstellaire, à plus de 170 UA : l’objet humain le plus lointain.",
    "Voyager 2": "La seule sonde à avoir visité les quatre géantes : Jupiter en 1979, Saturne en 1981, Uranus en 1986, Neptune en 1989. Après Neptune elle plonge vers le sud et franchit l’héliopause en novembre 2018.",
    "New Horizons": "Neuf ans et demi de voyage pour vingt-deux minutes de survol : le 14 juillet 2015 elle photographie Pluton pour la première fois, puis Arrokoth en 2019, l’objet le plus lointain jamais approché.",
    "Parker Solar Probe": "Passée à 6,1 millions de kilomètres du Soleil, dans la couronne, à 690 000 km/h : l’objet humain le plus rapide. Son bouclier de carbone encaisse 1 400 °C pendant que les instruments restent à température ambiante.",
    "Solar Orbiter": "Mission ESA et NASA qui incline peu à peu son orbite pour photographier les pôles du Soleil, invisibles depuis la Terre.",
    "JUICE": "Partie en 2023 pour Jupiter, elle doit se mettre en orbite autour de Ganymède en 2034 — une première autour d’une lune autre que la nôtre.",
    "Europa Clipper": "Lancée en 2024, elle survolera Europe une cinquantaine de fois à partir de 2030 pour sonder l’océan caché sous sa banquise.",
    "Lucy": "Douze ans de voyage pour visiter huit astéroïdes troyens, ces corps piégés sur l’orbite de Jupiter qui sont des fossiles de la formation du système solaire.",
    "Psyche": "Direction (16) Psyché, un astéroïde riche en métal qui pourrait être le noyau mis à nu d’une planète avortée.",
    "Juno": "En orbite polaire autour de Jupiter depuis 2016, elle plonge tous les 43 jours sous les ceintures de radiation pour sonder l’intérieur de la planète.",
    "BepiColombo": "Mission Europe-Japon vers Mercure : neuf survols de planètes pour freiner assez et se laisser capturer par la plus petite des orbites.",
    "OSIRIS-APEX": "Après avoir rapporté un échantillon de l’astéroïde Bennu en 2023, la sonde a été relancée vers Apophis, qu’elle rejoindra en 2029.",
    "Cassini": "Treize ans en orbite autour de Saturne, l’atterrisseur Huygens posé sur Titan, la découverte des geysers d’Encelade — puis une plongée volontaire dans l’atmosphère de Saturne le 15 septembre 2017 pour ne rien contaminer.",
    "Galileo": "Première sonde en orbite autour de Jupiter, de 1995 à 2003. Elle a largué une sonde dans l’atmosphère jovienne et révélé l’océan d’Europe.",
    "Rosetta": "Dix ans de voyage pour se mettre en orbite autour de la comète Tchouri en 2014 et y poser Philae : une première.",
    "Dawn": "La seule sonde à s’être mise en orbite autour de deux corps différents : Vesta en 2011, puis Cérès en 2015.",
    "Pioneer 10": "Première sonde à traverser la ceinture d'astéroïdes et à survoler Jupiter, en décembre 1973. Elle porte la plaque gravée d'un homme et d'une femme. Dernier signal reçu en janvier 2003 ; elle file toujours vers Aldébaran, qu'elle atteindrait dans deux millions d'années.",
    "Pioneer 11": "Jumelle de Pioneer 10, elle a ouvert la route de Saturne en 1979 en passant à 21 000 km des nuages — une trajectoire d'essai pour valider le passage des Voyager. Silencieuse depuis 1995.",
    "Ulysses": "La seule sonde à avoir survolé les pôles du Soleil. Un détour par Jupiter en 1992 a basculé son orbite à 79° du plan des planètes : elle a plongé trois fois au-dessus de chaque pôle solaire en dix-huit ans.",
    "MESSENGER": "Six survols de planètes et six ans de voyage pour freiner assez et se mettre en orbite autour de Mercure en 2011. Elle y a trouvé de la glace d'eau au fond de cratères jamais éclairés, avant de s'y écraser en 2015.",
    "Hayabusa2": "Elle a prélevé des échantillons de l'astéroïde Ryugu, dont de la matière sous-jacente exposée par un impacteur, et les a largués en Australie en décembre 2020. Elle poursuit sa route vers l'astéroïde 1998 KY26, prévu pour 2031.",
    "Hera": "Mission européenne partie en 2024 inspecter Dimorphos, l'astéroïde dévié par l'impact de DART en 2022. Elle doit mesurer précisément le cratère et la masse pour transformer l'essai en méthode.",
    "Tianwen-1": "Première mission chinoise vers Mars : orbiteur, atterrisseur et rover d'un coup, en 2021. Le rover Zhurong a roulé deux ans dans Utopia Planitia.",
    "Mars Express": "En orbite depuis 2003, c'est la plus ancienne sonde encore active autour de Mars. Son radar a détecté ce qui pourrait être de l'eau liquide sous la calotte sud.",
    "Akatsuki": "Ratée en 2010, sa mise en orbite autour de Vénus a été retentée cinq ans plus tard avec les petits propulseurs d'attitude — et a réussi. Elle a cartographié les vents de la super-rotation atmosphérique jusqu'en 2024.",
    "JWST": "Au point de Lagrange L2, à 1,5 million de kilomètres de la Terre, protégé du Soleil par un pare-soleil de la taille d'un court de tennis. Il observe dans l'infrarouge les premières galaxies formées après le Big Bang.",
    "ISS": "400 tonnes assemblées en orbite depuis 1998, habitées sans interruption depuis novembre 2000. Un tour de Terre en 92 minutes, soit seize levers de soleil par jour.",
    "Hubble": "En orbite depuis 1990, réparé cinq fois par des équipages de navette. Il observe de l’ultraviolet à l’infrarouge proche, au-dessus de l’atmosphère qui brouille tout.",
    "Tiangong": "La station chinoise, achevée en 2022 : trois modules et trois taïkonautes en permanence.",
    "GPS": "Une trentaine de satellites à 20 200 km répartis sur six plans : où que vous soyez, au moins quatre sont visibles à la fois, ce qui suffit à calculer une position et l’heure.",
    "Starlink": "Plusieurs milliers de satellites autour de 550 km d’altitude, la plus grande constellation jamais déployée. Quelques centaines seulement sont affichés ici.",
    "Prochaine mission orbitale": "Cap Canaveral tire vers l’est au-dessus de l’Atlantique pour profiter de la rotation terrestre, qui offre environ 400 m/s. La fenêtre affichée est illustrative : elle ne vient pas d’un manifeste de lancement réel.",
    "Mission d’observation": "Kourou se trouve à 5° de l’équateur, le site occidental le mieux placé pour les orbites géostationnaires. La fenêtre affichée est illustrative.",
    "Mission lunaire": "Tanegashima tire au-dessus du Pacifique depuis une île du sud du Japon. La fenêtre affichée est illustrative.",
]
